name: KFP e2e tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/e2e-test.yaml'
      - 'scripts/deploy/github/**'
      - 'go.mod'
      - 'go.sum'
      - 'backend/**'
      - 'frontend/**'
      - 'proxy/**'
      - 'manifests/kustomize/**'
      - 'test/**'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create k8s Kind Cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: kfp
          kubectl_version: v1.29.2
          version: v0.22.0
          node_image: kindest/node:v1.29.2
      - name: Build images
        run: ./scripts/deploy/github/build-images.sh
      - name: Deploy KFP
        run: ./scripts/deploy/github/deploy-kfp.sh
      - name: Forward API port
        run: ./scripts/deploy/github/forward-api-port.sh kubeflow
      - name: Initialization tests v1
        working-directory: ./backend/test/initialization
        run: go test -v ./... -namespace kubeflow -args -runIntegrationTests=true
      - name: Initialization tests v2
        working-directory: ./backend/test/v2/initialization
        run: go test -v ./... -namespace kubeflow -args -runIntegrationTests=true
      - name: API integration tests v1
        working-directory: ./backend/test/integration
        run: go test -v ./... -namespace ${NAMESPACE} -args -runIntegrationTests=true
      - name: API integration tests v2
        working-directory: ./backend/test/v2/integration
        run: go test -v ./... -namespace ${NAMESPACE} -args -runIntegrationTests=true
      - name: Frontend integration tests
        working-directory: ./test/frontend-integration-test
        run: ./run_test.sh
#      - name: Collect test results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: kfp-tekton-backend-artifacts
#          path: /tmp/tmp.*/*
