name: KFP e2e tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/e2e-test.yaml'
      - 'go.mod'
      - 'go.sum'
      - 'backend/**'
      - 'frontend/**'
      - 'proxy/**'
      - 'manifests/kustomize/**'
      - 'test/**'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create k8s Kind Cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: kfp
          kubectl_version: v1.29.2
          version: v0.22.0
          node_image: kindest/node:v1.29.2
      - name: build images
        run: ./scripts/deploy/github/build-images.sh
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: "deploy kfp-tekton"
        run: ./scripts/deploy/github/deploy-kfp.sh
      - name: Run Backend Tests
        run: go test -v ./... -namespace kubeflow -args -runIntegrationTests=true
      - name: Collect test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kfp-tekton-backend-artifacts
          path: /tmp/tmp.*/*
