name: KFP Kubernetes execution tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/kfp-kubernetes-execution-tests.yml'
      - 'sdk/python/**'
      - 'api/v2alpha1/**'
      - 'kubernetes_platform/**'

jobs:
  kfp-kubernetes-execution-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: kfp
          kubectl_version: v1.29.2
          version: v0.22.0
          node_image: kindest/node:v1.29.2

      - name: Build images
        run: ./scripts/deploy/github/build-images.sh

      - name: Deploy KFP
        run: ./scripts/deploy/github/deploy-kfp.sh

      - name: Forward API port
        run: ./scripts/deploy/github/forward-port.sh "kubeflow" "ml-pipeline" 8888 8888

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install protobuf-compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler -y

      - name: Install Wheel
        run: pip3 install wheel==0.42.0

      - name: Install protobuf
        run: pip3 install protobuf

      - name: make clean python
        working-directory: ./api
        run: make python

      - name: Install kfp-pipeline-spec from source
        run: |
          python3 -m pip install api/v2alpha1/python

      - name: Generate kfp-kubernetes proto files from source
        working-directory: ./kubernetes_platform
        run: make clean python

      - name: Install kfp-kubernetes from source
        run: |
          # rust needed for transitive deps in dev extras on Python:3.12
          sudo apt-get install rustc -y
          pip install -e ./kubernetes_platform/python[dev]

      - name: Install requirements
        run: pip install -r ./test/kfp-kubernetes-execution-tests/requirements.txt

      - name: Run tests
        run: |
          export KFP_ENDPOINT="http://localhost:8888"
          export TIMEOUT_SECONDS=2700
          pytest ./test/kfp-kubernetes-execution-tests/sdk_execution_tests.py --asyncio-task-timeout $TIMEOUT_SECONDS
