name: KFP e2e tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/test-prune.yaml'
      - 'scripts/deploy/github/**'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: kfp
          kubectl_version: v1.29.2
          version: v0.22.0
          node_image: kindest/node:v1.29.2

      - name: Build images
        run: ./scripts/deploy/github/build-images.sh
